### ISSUE TITLE
port to jackson-databind 2.5.x

### ISSUE THREAD

**Issue by puntogil** [pongasoft/utils-misc#6]
hi
create a patch for use jackson-databind-2.5.0
--- org.linkedin.util-groovy/src/main/java/org/linkedin/util/json/jackson/MetadataStyleSerializerFactory.java	2014-03-15 02:00:02.000000000 +0100
+++ org.linkedin.util-groovy/src/main/java/org/linkedin/util/json/jackson/MetadataStyleSerializerFactory.java.jackson-databind-2.5.0	2015-04-14 15:52:07.051170519 +0200
@@ -23,6 +23,7 @@
 import com.fasterxml.jackson.databind.module.SimpleSerializers;
 import com.fasterxml.jackson.databind.ser.BeanSerializerFactory;
 import com.fasterxml.jackson.databind.ser.std.BooleanSerializer;
+import com.fasterxml.jackson.databind.ser.std.NumberSerializer;
 import com.fasterxml.jackson.databind.ser.std.NumberSerializers;
 import com.fasterxml.jackson.databind.ser.std.StringSerializer;
 import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;
@@ -53,8 +54,8 @@
       new NumberSerializers.IntLikeSerializer();
     NumberSerializers.IntegerSerializer integerSerializer =
       new NumberSerializers.IntegerSerializer();
-    NumberSerializers.NumberSerializer numberSerializer =
-      new NumberSerializers.NumberSerializer();
+    NumberSerializer numberSerializer = 
+      new NumberSerializer();
     NumberSerializers.LongSerializer longSerializer =
       new NumberSerializers.LongSerializer();
     NumberSerializers.FloatSerializer floatSerializer =

regards

**Comment by ypujante** [comment]
Hi

1) I am not sure I understand the format of the message you sent: it looks like a patch but is not one. Did you want to do a pull request?
2) can you please provide some details on why to upgrade?

Thanks
Yan

**Comment by puntogil** [comment]
Hi,
thanks for the fast reply. I use and mantain FasterXML jackson packages on Fedora [1].
Practice our policy of packaging, we import only the
latest version of the software, and encourage to do the
same to other realities.
Sorry, for the malformed patch, but for me it's just a suggestion
for your use or just for my.
regards
[1] https://fedoraproject.org/wiki/Overview

**Comment by ypujante** [comment]
I will definitely look into it for a future version (like for example when upgrading to java 8) and bringing all libraries up to date. I do understand your philosophy but it is hard to just upgrade one thing without having massive regression. This project is used by glu and any change anywhere can have impact (for example glu uses json to store its model and depend on json pretty printing to compute a checksum of the model... if the latest version of jackson does it differently (or introduces a bug that is non existent in the version currently in use), then it will break functionalities).

This is why in general, I prefer to keep dependencies as stable as possible and then when a new major version is released, then bring all libraries up to date => that way we can test more deeply all sorts of potential regressions introduced by the upgrade and people are also aware that the release contains potential breaking changes and should be very cautious.

**Comment by puntogil** [comment]
Yes, i are aware that updating can produce compatibility/regression problems related

About, Crockfords json.org library is a very well known root of evil license problems.
Please try to replace it with one of the many free alternatives.

http://www.sonatype.com/people/2012/03/use-json-well-youd-better-not-be-evil/
http://tanguy.ortolo.eu/blog/article46/json-license

Android apparently has a replacement:
https://github.com/icedrobot/android-core/commit/014aa1a70743ae7e6ec0de1555f5b43d43844cf4

**Comment by puntogil** [comment]
https://android.googlesource.com/platform/libcore/+/android-5.1.0_r5/json/src/main/java/org/json

**Comment by ypujante** [comment]
Thank you for the heads up. I created a ticket to keep track of it: https://github.com/pongasoft/utils-misc/issues/7
